name: Update My Personal Hosts
on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm add axios

      - name: Generate Hosts
        run: node scripts/process.mjs

      - name: Deploy to Repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add hosts
          git commit -m "chore: 🚀 update hosts [$(date)]" || exit 0
          git push
